name: vinaigrette
version: '0.0.0'
github: "iupii/vinaigrette"
license: MIT
author: "Iurii Pachin"
maintainer: "Iurii Pachin"

extra-source-files:
  - LICENSE.md
  - package.yaml
  - README.md
  - stack.yaml

ghc-options:
  - -Wall
  #- -Werror

library:
  dependencies:
    - base
    - mtl
    - transformers
    - time
    - text
    - bytestring
    - aeson
    - hasql
    - resource-pool
    - fast-logger
    - wai
    - wai-extra
    - warp
    - servant
    - servant-server
    - servant-auth-server
    - data-default-class
  source-dirs: src

executables:
  vinaigrette:
    source-dirs: app
    main: Main.hs
    dependencies:
      - base
      - vinaigrette
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

_test-dependencies: &test-dependencies
  base: {}
  vinaigrette: {}
  tasty: {}
  tasty-discover: {}
  tasty-hspec: {}
  tasty-quickcheck: {}
  tasty-smallcheck: {}
  tasty-hedgehog: {}
  QuickCheck: {}
  hedgehog: {}
tests:
  servant-test-suite:
    source-dirs: tests/servant
    main: Tests.hs
    dependencies:
      <<: *test-dependencies
      text: {}
      http-client: {}
      warp: {}
      servant: {}
      servant-client: {}
      servant-server: {}
      fast-logger: {}
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

benchmarks:
  vinaigrette-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
      - base
      - vinaigrette
      - criterion
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
