resolver: lts-14.0
packages:
- .
extra-deps: []

# Travis
sudo: false
language: generic
cache:
  directories:
    - $HOME/.stack
before_install:
  - stack config set system-ghc --global true
  - export PATH=/opt/ghc/8.6.5/bin:$PATH
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-8.6.5
install:
  - stack --no-terminal --install-ghc test --only-dependencies
script:
  - stack --no-terminal test --haddock --no-haddock-deps
